---
abstract: 'Display RT API documentation online'
author:
  - 'Jesse Vincent <jesse@bestpractical.com>'
distribution_type: module
generated_by: 'Module::Install version 0.770'
license: GPLv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-OnlineDocs
no_index:
  directory:
    - etc
    - html
    - po
    - var
    - inc
requires:
  File::Basename: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Pod::Simple::HTML: 0
  perl: 5.8.3
version: 0.10
