---
abstract: 'RT OnlineDocs Extension'
author:
  - 'Jesse Vincent - <jesse@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-OnlineDocs
no_index:
  directory:
    - html
    - inc
requires:
  File::Basename: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Pod::Simple::HTML: 0
  perl: 5.8.3
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 1.0
